### ISSUE TITLE
'FAILED', u'ScapyLibrary', AttributeError("'UserErrorHandler' object has no attribute 'library'",)

### ISSUE THREAD

**Issue by handa417** [rainmanwy/robotframework-ScapyLibrary#8]
With the following python libs, create a project on ride. I add libs as ftplibrary, selenium2library are ok, but add ScapyLibrary failed.
python   2.7.13
robotframework                  3.1.1
robotframework-ftplibrary       1.6
robotframework-ride             1.7.3
robotframework-ScapyLibrary     0.1.4
robotframework-selenium2library 3.0.0
scapy                           2.4.2

('FAILED', u'ScapyLibrary', AttributeError("'UserErrorHandler' object has no attribute 'library'",))
20190521 14:49:40.633 [WARN]: Importing test library "ScapyLibrary" failed

Traceback (most recent call last):
'UserErrorHandler' object has no attribute 'library'
  File "E:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "E:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 32, in get_import_result
    ) for kw in lib.handlers]

**Comment by rainmanwy** [comment]
@handa417 , could you install the latest version from pypi. And have a try again?

**Comment by handa417** [comment]
@rainmanwy Thank you for your update. Use the latest version, the issue is same as 0.1.4.

20190522 09:36:51.407 [INFO]: Found Robot Framework version 3.1.1 from E:\Python27\lib\site-packages\robot.

20190522 09:36:51.408 [INFO]: Started RIDE 1.7.3.1 using python version 2.7.13 with wx version 4.0.5 in win32.

20190522 09:36:57.743 [WARN]: Importing test library "ScapyLibrary" failed

Traceback (most recent call last):
'UserErrorHandler' object has no attribute 'library'
  File "E:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "E:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 32, in get_import_result
    ) for kw in lib.handlers]

**Comment by rainmanwy** [comment]
@handa417 , could you have a try to import ScapyLibrary from command line. for example:
```
python -c "from ScapyLibrary import ScapyLibrary;s=ScapyLibrary()"
```

As the error you provided is only related with code of RIDE. Not sure what happened with ScapyLibrary.

**Comment by handa417** [comment]
@rainmanwy ，Import ScapyLibrary from command line as follows:
E:\Python27\Scripts>python -c "from ScapyLibrary import ScapyLibrary;s=ScapyLibrary()"
*DEBUG* temp solution

E:\Python27\Scripts>

**Comment by rainmanwy** [comment]
@handa417 , you could execute test case from command line.
As least from the information, ScapyLibrary does not report any errors in your environment.

**Comment by handa417** [comment]
@rainmanwy, I did a simple test and added a keyword to read pcapng, found that the keyword has not been executed via log.
`read pcap file    E:\\Auto_test\\CPE\\TEST\\QOS\\web_login.pcapng`
![image](https://user-images.githubusercontent.com/50862447/58152863-35c18f80-7ca0-11e9-8168-3f9b80c2a477.png)


E:\Python27\Scripts>robot E:\Auto_test\CPE
[ WARN ] [bgp.py] use_2_bytes_asn: True
[ ERROR ] Loading module scapy.layers.cansocket_native
[ ERROR ] Loading module scapy.layers.cansocket_python_can
[ WARN ] CARP overwrites VRRP !
[ ERROR ] Error in test library 'ScapyLibrary': Creating keyword 'Dns Get Str' failed: Keyword with same name defined multiple times.
[ ERROR ] Error in test library 'ScapyLibrary': Creating keyword 'IE ChargingID' failed: Keyword with same name defined multiple times.
[ ERROR ] Error in test library 'ScapyLibrary': Creating keyword 'IE APNRestriction' failed: Keyword with same name defined multiple times.
[ ERROR ] Error in test library 'ScapyLibrary': Creating keyword 'Raw' failed: Keyword with same name defined multiple times.
[ ERROR ] Error in test library 'ScapyLibrary': Creating keyword 'PPP' failed: Keyword with same name defined multiple times.
CPE.TEST.QOS :: Initialization file test suites
CPE.TEST.QOS.QOS TEST
802.1P                                                               
DevTools listening on ws://127.0.0.1:61206/devtools/browser/b86e6c30-f990-433a-bd6d-8b5409434da6
802.1P                                                                | PASS |
 
CPE.TEST.QOS.QOS TEST                                                 | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed

CPE.TEST.QOS :: Initialization file test suites                       | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed


CPE.TEST                                                              | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed


CPE                                                                   | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed


Output:  E:\Python27\Scripts\output.xml
Log:     E:\Python27\Scripts\log.html
Report:  E:\Python27\Scripts\report.html

**Comment by rainmanwy** [comment]
@handa417 , could you use -L Trace option to execute your example.
By the way, this keyword will return packet list, and you could log it.

**Comment by handa417** [comment]
@rainmanwy , The keyword could execute, but -L Trace option did not track useful information.
![image](https://user-images.githubusercontent.com/50862447/58157841-cc477e00-7cab-11e9-8ae3-1cc984773028.png)
![image](https://user-images.githubusercontent.com/50862447/58157879-d8334000-7cab-11e9-90a0-d27b4c9a0030.png)

**Comment by rainmanwy** [comment]
@handa417 , this is correct.
This keyword return "PacketList" object (scapy).
You could use for loop to log each packet
