### ISSUE TITLE
Please add library spec to be imported in RIDE

### ISSUE THREAD

**Issue by HelioGuilherme66** [rainmanwy/robotframework-ScapyLibrary#9]
Hello @rainmanwy 
Thank you so much for all the libraries you created.

Please include the library spec for users to import in RIDE.
Thanks.

Generated today:
[ScapyLibrary.zip](https://github.com/rainmanwy/robotframework-ScapyLibrary/files/3247695/ScapyLibrary.zip)

**Comment by rainmanwy** [comment]
@HelioGuilherme66 , thank you very much!

So this xml file is generated with rf libdoc, right?
And this file should be in root folder of this library, right?

**Comment by HelioGuilherme66** [comment]
Yes, at least RIDE finds it when in the root.

**Comment by rainmanwy** [comment]
Thanks @HelioGuilherme66 , it should be ok now. XML will be created when execute setup command
